variables:
    ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.1.1
    endpoint: 'GitHub (ESFA)'

jobs:

# Build the app with the dfc-dotnetcore-build template.  Runs if the output of TestBranchName is Version2+
- job: BuildArmTemplate
  displayName: Build-ArmTemplate
  pool:
    name: Continuous Integration 02 - SSD - 160ACU
    demands:
    - msbuild
    - visualstudio

  variables:
    TestArmTemplateScriptUrl: https://raw.githubusercontent.com/SkillsFundingAgency/dfc-devops/NCSD-628-AddResourcesForTestingArm/Scripts/Test-ArmTemplate.ps1
    TestArmTemplateScriptFilePath: $(System.DefaultWorkingDirectory)\Test-ArmTemplate.ps1

  steps:
  - task: PowerShell@2
    name: DownloadTestArmTemplateScript
    displayName: 'Download Test-ArmTemplate script'
    inputs:
     targetType: 'inline'
     script: Invoke-WebRequest -Uri $(TestArmTemplateScriptUrl) -OutFile $(TestArmTemplateScriptFilePath)
  - task: AzurePowerShell@3
    displayName: 'Test Arm Template'
    inputs:
      azureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      scriptType: filePath
      scriptPath: $(TestArmTemplateScriptFilePath)
      scriptArguments: -ParameterFile "$(ArmTemplateRoot)\parameters.json" -TemplateFile "$(ArmTemplateRoot)\template.json" -Verbose
      azurePowerShellVersion: LatestVersion
  - task: CopyFiles@2
    displayName: 'Copy Arm Templates to Staging'
    inputs:
      SourceFolder: '$(ArmTemplateRoot)\'
      TargetFolder: $(build.artifactstagingdirectory)/ArmTemplates
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: 'Azure'
